const FAMILY_DATA = {
    "Mimit": [],
    "Oree": ["Crystal Bite", "Frond Whip", "Telekinetic Shrapnel", "Wastewater"],
    "Halzhi": ["Autodestruction", "Turbo Attack"],
    // Chromeon Variants (Digital + Subtype)
    "Chromeon (Neutral)": [],
    "Chromeon (Fire)": [],
    "Chromeon (Water)": [],
    "Chromeon (Nature)": [],
    "Chromeon (Electric)": [],
    "Chromeon (Earth)": [],
    "Chromeon (Mental)": [],
    "Chromeon (Wind)": [],
    "Chromeon (Digital)": [],
    "Chromeon (Melee)": [],
    "Chromeon (Crystal)": [],
    "Chromeon (Toxic)": [],
    "Platypet": ["Antitoxins", "Flood", "Sharp Rain", "Urushiol"],
    "Swali": ["Hurricane", "Spores"],
    "Tateru": ["Held Anger", "Inner Spirit", "Knockback", "Perfect Jab"],
    "Gharunder": ["Shelter", "Waterjet"],
    "Mosu": ["Soul Shout", "Warm Cuddle"],
    "Paharo": ["Humiliating Slap", "Tornado"],
    "Ampling": ["Allergic Spread", "Burrow", "Roots"],
    "Bunbun": ["Crystal Bite", "Dust Vortex"],
    "Hidody": ["Bark Shield", "Hypoxia", "Intimidation", "Spores"],
    "Fomu": ["Hyperkinetic Strike", "Ice Shuriken", "Lullaby", "Sharp Rain"],
    "Skail": ["Oshi-Dashi", "Perfect Jab"],
    "Goty": ["Bestial Charge", "Burrow", "Head Charge"],
    "Rhoulder": ["Burrow", "Toughen"],
    "Houchic": ["Strangle"],
    "Orphyll": ["Bark Shield", "Narcoleptic Hit", "Photosynthesis"],
    "Banapi": ["Roar", "Shelter"],
    "Lapinite": ["Diamond Fort", "Mineral Hail"],
    "Reval": ["Hallucination", "Matter Teleport"],
    "Bigu": ["Bubbles", "Ice Cubes", "Revitalize", "Toxic Slime"],
    "0b1": ["Bush", "Digithreat", "Sparks", "Tesla Prison"],
    "Kaku": ["Lifeful Sap", "Petal Dagger"],
    "Valash": ["Clinch", "Ninja Jutsu", "Quartz Shield"],
    "Towly": ["Beta Burst", "Energy Manipulation", "Lullaby", "Oshi-Dashi"],
    "Gyalis": ["Crystal Spikes", "Crystallize", "Earth Wave"],
    "Occlura": ["Humiliating Slap", "Psy Surge"],
    "Raiber": ["Rampage"],
    "Pewki": ["Cold Geyser", "Flood", "High-pressure Water", "Revitalize"],
    "Scarawatt": ["Shelter", "Toughen"],
    "Hoglip": ["Hellfire", "Hook", "Rampage"],
    "Osuchi": ["Dust Vortex", "Footwork", "Jinxed Whisper", "Martial Strike"],
    "Saipat": ["Ice Cubes", "Ice Shuriken", "Toxic Ink"],
    "Pycko": ["Mud Shower"],
    "Crystle": ["Antitoxins", "Crystal Deluge", "Quartz Shield"],
    "Innki": ["Chain Heal", "Pickpocket", "Tesla Prison", "Thunder Strike"],
    "Shaolite": ["Lullaby", "Unseen Blow"],
    "Cycrox": ["Paralyzing Poison"],
    "Hocus": ["Extra Energy Slam", "Pickpocket"],
    "Smolzy": ["Rage", "Show Off", "Sparkling Bullet", "Wrenching Massage"],
    "Mushi": ["Inner Spirit", "Intimidation", "Virulent Gust"],
    "Magmis": ["Warm Cuddle"],
    "Umishi": ["Flood"],
    "Galvanid": ["Piezoelectric Blow", "Turbine"],
    "Smazee": ["Dim Mak", "Earth Wave", "Hook"],
    "Zizare": ["Burrow", "Jinxed Whisper"],
    "Gorong": ["Meditation"],
    "Mitty": ["Strangle", "Matter Teleport", "Hypnosis"],
    "Momo": ["Knockback"],
    "Kuri": ["Earthbreaker", "Toughen"],
    "Spriole": ["Frond Whip", "Spores"],
    "Toxolotl": ["Narcoleptic Hit", "Pollution"],
    "Blooze": ["Metabolize", "Rotten Goo"],
    "Zephyruff": ["Feather Gatling", "Gust"],
    "Grumvel": ["Goring", "Sludge Gift"],
    "Ganki": ["Tesla Prison", "Turbine"],
    "Oceara": ["Chain Heal", "Sharp Rain"],
    "Yowlar": ["Ice Cubes", "Toughen"],
    "Droply": ["Waterjet", "Ice Cubes"],
    "Broccoblin": ["Bark Shield", "Frond Whip", "Soul Shout", "Hook Kick"],
    "Shuine": ["Mirror Shell", "Quartz Shield"],
    "Nessla": ["Aquatic Whirlwind", "Bright Beam"],
    "Valiar": [],
    "Pupoise": ["Bush", "Energy Manipulation", "Sacrifice"],
    "Kalazu": ["Clinch", "Iced Stalactite", "Humiliating Slap"],
    "Adoroboros": ["Held Anger", "Hypnosis", "Inner Spirit", "Virulent Gust"],
    "Tuwai": [],
    "Kinu": ["Denigrate"],
    "Vulvir": ["Earth Wave", "Extinction", "Hook"],
    "Pigepic": ["Head Charge", "Hurricane", "Sharp Rain"],
    "Akranox": ["Earth Wave", "Toughen"],
    // Koish Variants (Water + Subtype)
    "Koish (Neutral)": ["Autodestruction"],
    "Koish (Fire)": ["Autodestruction"],
    "Koish (Water)": ["Autodestruction"],
    "Koish (Nature)": ["Autodestruction"],
    "Koish (Electric)": ["Autodestruction"],
    "Koish (Earth)": ["Autodestruction"],
    "Koish (Mental)": ["Autodestruction"],
    "Koish (Wind)": ["Autodestruction"],
    "Koish (Digital)": ["Autodestruction"],
    "Koish (Melee)": ["Autodestruction"],
    "Koish (Crystal)": ["Autodestruction"],
    "Koish (Toxic)": ["Autodestruction"],
    "Vulffy": ["Bush"],
    "Chubee": ["Blue Screen", "Hologram", "Metabolize", "Plasma Beam"],
    "Mawtle": ["Digithreat", "Fiery Heist", "Spores"],
    "Hazrat": ["Heat Up"],
    "Minttle": ["Thunder Strike", "Turbo Charge", "Ultrasound"],
    "Maoala": ["Haito Uchi"],
    "Venx": ["Ninja Jutsu"],
    "Chimurian": ["Mirror Shell"],
    "Arachnyte": ["Crystal Spikes", "Soul Shout", "Thunder Strike", "Water Cannon"],
    "Thaiko": ["Unseen Blow"],
    "Anahir": ["Fiery Heist"],
    "Tyranak": [],
    "Volgon": [],
    "Galios": []
};

const TEM_DATABASE = {
    "Mimit": { family: "Mimit", type: ["Digital"], parent_moves: [] },
    "Oree": { family: "Oree", type: ["Digital"], parent_moves: ["Tesla Prison", "Turbo Attack"] },
    "Zaobian": { family: "Oree", type: ["Digital"], parent_moves: ["Tesla Prison", "Turbo Attack", "Hologram"] },
    "Halzhi": { family: "Halzhi", type: ["Digital"], parent_moves: ["Hologram", "Plasma Beam"] },
    "Molgu": { family: "Halzhi", type: ["Digital"], parent_moves: ["Hologram", "Plasma Beam", "Blue Screen", "Digithreat"] },
    
    // Chromeon Variants (Always Primary: Digital)
    "Chromeon (Neutral)": { family: "Chromeon (Neutral)", type: ["Digital", "Neutral"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Fire)": { family: "Chromeon (Fire)", type: ["Digital", "Fire"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Water)": { family: "Chromeon (Water)", type: ["Digital", "Water"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Nature)": { family: "Chromeon (Nature)", type: ["Digital", "Nature"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Electric)": { family: "Chromeon (Electric)", type: ["Digital", "Electric"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Earth)": { family: "Chromeon (Earth)", type: ["Digital", "Earth"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Mental)": { family: "Chromeon (Mental)", type: ["Digital", "Mental"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Wind)": { family: "Chromeon (Wind)", type: ["Digital", "Wind"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Digital)": { family: "Chromeon (Digital)", type: ["Digital"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Melee)": { family: "Chromeon (Melee)", type: ["Digital", "Melee"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Crystal)": { family: "Chromeon (Crystal)", type: ["Digital", "Crystal"], parent_moves: ["Digithreat", "Hologram"] },
    "Chromeon (Toxic)": { family: "Chromeon (Toxic)", type: ["Digital", "Toxic"], parent_moves: ["Digithreat", "Hologram"] },

    "Platypet": { family: "Platypet", type: ["Water", "Toxic"], parent_moves: ["Antitoxins", "Flood", "Sharp Rain", "Toxic Slime"] },
    "Platox": { family: "Platypet", type: ["Water", "Toxic"], parent_moves: ["Antitoxins", "Flood", "Held Anger", "Sharp Rain", "Toxic Slime"] },
    "Platimous": { family: "Platypet", type: ["Water", "Toxic"], parent_moves: ["Antitoxins", "Aquatic Whirlwind", "Flood", "Held Anger", "Rotten Goo", "Sharp Rain", "Toxic Slime"] },
    "Swali": { family: "Swali", type: ["Nature"], parent_moves: ["Allergic Spread", "Bark Shield", "Photosynthesis", "Spores"] },
    "Loali": { family: "Swali", type: ["Nature", "Wind"], parent_moves: ["Allergic Spread", "Bark Shield", "Gust", "Photosynthesis", "Spores"] },
    "Tateru": { family: "Tateru", type: ["Neutral"], parent_moves: ["Bestial Charge", "Knockback", "Perfect Jab"] },
    "Gharunder": { family: "Gharunder", type: ["Toxic", "Electric"], parent_moves: ["Metabolize", "Paralyzing Poison", "Piezoelectric Blow", "Shelter", "Tesla Prison"] },
    "Mosu": { family: "Mosu", type: ["Earth"], parent_moves: ["Show Off", "Soul Shout"] },
    "Magmut": { family: "Mosu", type: ["Earth", "Fire"], parent_moves: ["Show Off", "Soul Shout", "Oshi-Dashi", "Rampage"] },
    "Paharo": { family: "Paharo", type: ["Wind"], parent_moves: ["Feather Gatling"] },
    "Paharac": { family: "Paharo", type: ["Wind"], parent_moves: ["Feather Gatling"] },
    "Granpah": { family: "Paharo", type: ["Wind"], parent_moves: ["Feather Gatling", "Gust", "Hurricane"] },
    "Ampling": { family: "Ampling", type: ["Electric"], parent_moves: ["Bright Beam", "Sparks", "Thunder Strike", "Turbo Charge"] },
    "Amphatyr": { family: "Ampling", type: ["Electric", "Nature"], parent_moves: ["Bright Beam", "Sparks", "Thunder Strike", "Turbo Charge", "Intimidation", "Shelter", "Tesla Prison"] },
    "Bunbun": { family: "Bunbun", type: ["Earth", "Crystal"], parent_moves: ["Crystal Deluge", "Dust Vortex", "Mud Shower"] },
    "Mudrid": { family: "Bunbun", type: ["Earth", "Crystal"], parent_moves: ["Crystal Deluge", "Dust Vortex", "Mud Shower", "Diamond Fort", "Earth Wave", "Footwork"] },
    "Hidody": { family: "Hidody", type: ["Nature"], parent_moves: ["Allergic Spread", "Bark Shield", "Spores"] },
    "Taifu": { family: "Hidody", type: ["Nature"], parent_moves: ["Allergic Spread", "Bark Shield", "Frond Whip", "Spores"] },
    "Fomu": { family: "Fomu", type: ["Water"], parent_moves: ["Bubbles", "Ice Cubes", "Ice Shuriken", "Sharp Rain"] },
    "Wiplump": { family: "Fomu", type: ["Water", "Wind"], parent_moves: ["Bubbles", "Ice Cubes", "Ice Shuriken", "Sharp Rain", "Gust", "Head Charge", "Lullaby", "Tornado"] },
    "Skail": { family: "Skail", type: ["Neutral"], parent_moves: ["Held Anger", "Ninja Jutsu", "Perfect Jab"] },
    "Skunch": { family: "Skail", type: ["Neutral", "Melee"], parent_moves: ["Held Anger", "Ninja Jutsu", "Perfect Jab", "Haito Uchi", "Inner Spirit", "Martial Strike", "Oshi-Dashi", "Wrenching Massage"] },
    "Goty": { family: "Goty", type: ["Neutral"], parent_moves: ["Burrow"] },
    "Mouflank": { family: "Goty", type: ["Neutral"], parent_moves: ["Burrow", "Held Anger", "Knockback"] },
    "Rhoulder": { family: "Rhoulder", type: ["Neutral", "Earth"], parent_moves: ["Bestial Charge", "Burrow", "Earthbreaker", "Goring", "Held Anger", "Toughen"] },
    "Houchic": { family: "Houchic", type: ["Mental"], parent_moves: ["Beta Burst", "Energy Manipulation", "Humiliating Slap", "Hypnosis", "Psy Surge", "Strangle"] },
    "Tental": { family: "Houchic", type: ["Mental"], parent_moves: ["Beta Burst", "Energy Manipulation", "Humiliating Slap", "Hypnosis", "Psy Surge", "Strangle", "Ninja Jutsu"] },
    "Nagaise": { family: "Houchic", type: ["Mental", "Water"], parent_moves: ["Beta Burst", "Energy Manipulation", "Humiliating Slap", "Hypnosis", "Psy Surge", "Strangle", "Ninja Jutsu", "High-pressure Water"] },
    "Orphyll": { family: "Orphyll", type: ["Nature", "Toxic"], parent_moves: ["Allergic Spread", "Antitoxins", "Bark Shield", "Held Anger", "Hypnosis", "Narcoleptic Hit", "Roots", "Spores"] },
    "Nidrasil": { family: "Orphyll", type: ["Nature", "Toxic"], parent_moves: ["Allergic Spread", "Antitoxins", "Bark Shield", "Held Anger", "Hypnosis", "Narcoleptic Hit", "Roots", "Spores"] },
    "Banapi": { family: "Banapi", type: ["Fire"], parent_moves: ["Heat Up", "Rampage", "Shelter", "Warm Cuddle"] },
    "Capyre": { family: "Banapi", type: ["Fire"], parent_moves: ["Heat Up", "Rampage", "Shelter", "Warm Cuddle", "Extinction", "Fiery Heist"] },
    "Lapinite": { family: "Lapinite", type: ["Crystal"], parent_moves: [] },
    "Azuroc": { family: "Lapinite", type: ["Crystal"], parent_moves: ["Crystal Bite", "Crystal Spikes", "Quartz Shield"] },
    "Zenoreth": { family: "Lapinite", type: ["Crystal"], parent_moves: ["Crystal Bite", "Crystal Spikes", "Quartz Shield", "Crystal Deluge"] },
    "Reval": { family: "Reval", type: ["Mental"], parent_moves: ["Hypnosis", "Matter Teleport", "Psy Surge"] },
    "Aohi": { family: "Reval", type: ["Mental", "Fire"], parent_moves: ["Hypnosis", "Matter Teleport", "Psy Surge"] },
    "Bigu": { family: "Bigu", type: ["Nature"], parent_moves: [] },
    "Babawa": { family: "Bigu", type: ["Nature", "Water"], parent_moves: ["Antitoxins", "Aquatic Whirlwind", "Ice Cubes", "Iced Stalactite", "Revitalize"] },
    "0b1": { family: "0b1", type: ["Digital", "Electric"], parent_moves: ["Bush", "Digithreat", "Plasma Beam", "Tesla Prison"] },
    "0b10": { family: "0b1", type: ["Digital", "Electric"], parent_moves: ["Bush", "Digithreat", "Plasma Beam", "Tesla Prison"] },
    "Kaku": { family: "Kaku", type: ["Nature"], parent_moves: ["Allergic Spread", "Narcoleptic Hit"] },
    "Saku": { family: "Kaku", type: ["Nature", "Wind"], parent_moves: ["Allergic Spread", "Bark Shield", "Frond Whip", "Humiliating Slap", "Hypoxia", "Narcoleptic Hit", "Turbine"] },
    "Valash": { family: "Valash", type: ["Neutral", "Crystal"], parent_moves: ["Crystal Bite", "Crystal Spikes", "Held Anger", "Ninja Jutsu", "Quartz Shield"] },
    "Towly": { family: "Towly", type: ["Melee", "Mental"], parent_moves: ["Energy Manipulation", "Intimidation", "Lullaby", "Oshi-Dashi"] },
    "Owlhe": { family: "Towly", type: ["Wind", "Melee"], parent_moves: ["Intimidation", "Lullaby", "Oshi-Dashi", "Perfect Jab", "Turbine", "Wrenching Massage"] },
    "Barnshe": { family: "Towly", type: ["Wind", "Mental"], parent_moves: [] },
    "Gyalis": { family: "Gyalis", type: ["Crystal", "Melee"], parent_moves: ["Antitoxins", "Crystal Bite", "Earth Wave", "Footwork", "Hook Kick", "Ninja Jutsu"] },
    "Occlura": { family: "Occlura", type: ["Crystal"], parent_moves: ["Crystal Bite", "Crystallize"] },
    "Myx": { family: "Occlura", type: ["Crystal", "Mental"], parent_moves: ["Clinch", "Crystal Bite", "Crystal Spikes", "Crystallize", "Denigrate", "Energy Manipulation", "Hallucination", "Pickpocket"] },
    "Raiber": { family: "Raiber", type: ["Fire"], parent_moves: ["Rampage"] },
    "Raize": { family: "Raiber", type: ["Fire"], parent_moves: ["Rampage"] },
    "Raican": { family: "Raiber", type: ["Fire"], parent_moves: ["Rampage"] },
    "Pewki": { family: "Pewki", type: ["Water"], parent_moves: ["Bubbles", "Flood", "Humiliating Slap", "Revitalize"] },
    "Piraniant": { family: "Pewki", type: ["Water"], parent_moves: ["Aquatic Whirlwind", "Bubbles", "Flood", "Humiliating Slap", "Ice Cubes", "Revitalize", "Waterjet"] },
    "Scarawatt": { family: "Scarawatt", type: ["Electric"], parent_moves: ["Burrow", "Shelter", "Thunder Strike"] },
    "Scaravolt": { family: "Scarawatt", type: ["Electric", "Fire"], parent_moves: ["Burrow", "Shelter", "Thunder Strike"] },
    "Hoglip": { family: "Hoglip", type: ["Digital", "Fire"], parent_moves: ["Hook", "Plasma Beam", "Rampage"] },
    "Hedgine": { family: "Hoglip", type: ["Digital", "Fire"], parent_moves: ["Hook", "Plasma Beam", "Rampage"] },
    "Osuchi": { family: "Osuchi", type: ["Earth"], parent_moves: ["Dust Vortex", "Jinxed Whisper", "Toughen"] },
    "Osukan": { family: "Osuchi", type: ["Earth", "Melee"], parent_moves: ["Dust Vortex", "Jinxed Whisper", "Meditation", "Toughen"] },
    "Osukai": { family: "Osuchi", type: ["Earth", "Melee"], parent_moves: ["Dim Mak", "Dust Vortex", "Earthbreaker", "Hook", "Inner Spirit", "Jinxed Whisper", "Meditation", "Toughen", "Wrenching Massage"] },
    "Saipat": { family: "Saipat", type: ["Water", "Melee"], parent_moves: ["Clinch", "High-pressure Water", "Ice Cubes", "Ice Shuriken", "Iced Stalactite", "Martial Strike", "Ninja Jutsu", "Rage", "Waterjet", "Wrenching Massage"] },
    "Pycko": { family: "Pycko", type: ["Earth", "Fire"], parent_moves: ["Burrow", "Heat Up"] },
    "Drakash": { family: "Pycko", type: ["Earth", "Fire"], parent_moves: ["Burrow", "Heat Up", "Hellfire", "Toughen"] },
    "Crystle": { family: "Crystle", type: ["Crystal"], parent_moves: ["Crystal Spikes", "Mirror Shell", "Quartz Shield"] },
    "Sherald": { family: "Crystle", type: ["Crystal"], parent_moves: ["Crystal Spikes", "Diamond Fort", "Mirror Shell", "Quartz Shield"] },
    "Tortenite": { family: "Crystle", type: ["Crystal", "Toxic"], parent_moves: ["Antitoxins", "Crystal Spikes", "Diamond Fort", "Mirror Shell", "Quartz Shield", "Rotten Goo"] },
    "Innki": { family: "Innki", type: ["Electric", "Crystal"], parent_moves: ["Bright Beam", "Diamond Fort", "Mineral Hail", "Piezoelectric Blow", "Sparkling Bullet", "Sparks", "Tesla Prison", "Thunder Strike"] },
    "Shaolite": { family: "Shaolite", type: ["Melee"], parent_moves: ["Lullaby", "Martial Strike", "Unseen Blow"] },
    "Shaolant": { family: "Shaolite", type: ["Melee"], parent_moves: ["Dim Mak", "Inner Spirit", "Lullaby", "Martial Strike", "Soul Shout", "Unseen Blow"] },
    "Cycrox": { family: "Cycrox", type: ["Digital", "Toxic"], parent_moves: ["Digithreat", "Hologram", "Metabolize", "Wastewater"] },
    "Hocus": { family: "Hocus", type: ["Mental"], parent_moves: ["Beta Burst", "Hypnosis"] },
    "Pocus": { family: "Hocus", type: ["Mental"], parent_moves: ["Beta Burst", "Denigrate", "Hypnosis", "Ninja Jutsu"] },
    "Smolzy": { family: "Smolzy", type: ["Electric"], parent_moves: ["Tesla Prison"] },
    "Sparzy": { family: "Smolzy", type: ["Electric"], parent_moves: ["Tesla Prison"] },
    "Golzy": { family: "Smolzy", type: ["Electric", "Melee"], parent_moves: ["Footwork", "Oshi-Dashi", "Tesla Prison"] },
    "Mushi": { family: "Mushi", type: ["Toxic"], parent_moves: ["Humiliating Slap", "Inner Spirit", "Urushiol", "Virulent Gust"] },
    "Mushook": { family: "Mushi", type: ["Toxic", "Melee"], parent_moves: ["Footwork", "Humiliating Slap", "Inner Spirit", "Perfect Jab", "Urushiol", "Virulent Gust"] },
    "Magmis": { family: "Magmis", type: ["Fire"], parent_moves: [] },
    "Mastione": { family: "Magmis", type: ["Fire", "Water"], parent_moves: ["High-pressure Water", "Sharp Rain", "Warm Cuddle"] },
    "Umishi": { family: "Umishi", type: ["Water"], parent_moves: ["Aquatic Whirlwind", "Flood", "Sharp Rain"] },
    "Ukama": { family: "Umishi", type: ["Water"], parent_moves: ["Aquatic Whirlwind", "Flood", "Sharp Rain"] },
    "Galvanid": { family: "Galvanid", type: ["Electric"], parent_moves: ["Sparkling Bullet", "Sparks", "Tesla Prison", "Turbine"] },
    "Raignet": { family: "Galvanid", type: ["Electric"], parent_moves: ["Sparkling Bullet", "Sparks", "Tesla Prison", "Thunder Strike", "Turbine", "Ultrasound"] },
    "Smazee": { family: "Smazee", type: ["Melee"], parent_moves: ["Earth Wave", "Intimidation", "Martial Strike", "Perfect Jab", "Show Off"] },
    "Baboong": { family: "Smazee", type: ["Melee"], parent_moves: ["Earth Wave", "Intimidation", "Martial Strike", "Perfect Jab", "Show Off"] },
    "Seismunch": { family: "Smazee", type: ["Melee", "Earth"], parent_moves: ["Earth Wave", "Footwork", "Hook", "Inner Spirit", "Intimidation", "Martial Strike", "Perfect Jab", "Show Off", "Wrenching Massage"] },
    "Zizare": { family: "Zizare", type: ["Earth"], parent_moves: ["Burrow", "Jinxed Whisper", "Sludge Gift"] },
    "Gorong": { family: "Gorong", type: ["Melee"], parent_moves: ["Hook Kick", "Intimidation", "Show Off", "Wrenching Massage"] },
    "Mitty": { family: "Mitty", type: ["Mental"], parent_moves: ["Hypnosis", "Matter Teleport", "Strangle"] },
    "Sanbi": { family: "Mitty", type: ["Mental"], parent_moves: ["Hypnosis", "Lullaby", "Matter Teleport", "Strangle"] },
    "Momo": { family: "Momo", type: ["Neutral"], parent_moves: ["Head Charge", "Knockback"] },
    "Kuri": { family: "Kuri", type: ["Earth"], parent_moves: ["Burrow", "Sludge Gift", "Toughen"] },
    "Kauren": { family: "Kuri", type: ["Earth"], parent_moves: ["Burrow", "Earth Wave", "Footwork", "Goring", "Sludge Gift", "Toughen"] },
    "Spriole": { family: "Spriole", type: ["Nature"], parent_moves: ["Allergic Spread", "Frond Whip", "Petal Dagger", "Revitalize", "Roots", "Spores"] },
    "Deendre": { family: "Spriole", type: ["Nature"], parent_moves: ["Allergic Spread", "Frond Whip", "Petal Dagger", "Revitalize", "Roots", "Spores"] },
    "Cerneaf": { family: "Spriole", type: ["Nature"], parent_moves: ["Allergic Spread", "Bush", "Frond Whip", "Petal Dagger", "Revitalize", "Roots", "Spores"] },
    "Toxolotl": { family: "Toxolotl", type: ["Toxic"], parent_moves: ["Hypnosis", "Narcoleptic Hit"] },
    "Noxolotl": { family: "Toxolotl", type: ["Toxic"], parent_moves: ["Hypnosis", "Narcoleptic Hit", "Virulent Gust"] },
    "Blooze": { family: "Blooze", type: ["Toxic"], parent_moves: [] },
    "Goolder": { family: "Blooze", type: ["Toxic"], parent_moves: ["Antitoxins", "Pollution"] },
    "Zephyruff": { family: "Zephyruff", type: ["Toxic", "Wind"], parent_moves: [] },
    "Volarend": { family: "Zephyruff", type: ["Toxic", "Wind"], parent_moves: ["Hyperkinetic Strike", "Tornado", "Virulent Gust"] },
    "Grumvel": { family: "Grumvel", type: ["Earth"], parent_moves: [] },
    "Grumper": { family: "Grumvel", type: ["Earth", "Electric"], parent_moves: ["Dust Vortex", "Earthbreaker", "Tesla Prison", "Thunder Strike"] },
    "Ganki": { family: "Ganki", type: ["Electric", "Wind"], parent_moves: ["Sparks", "Tesla Prison", "Turbine"] },
    "Gazuma": { family: "Ganki", type: ["Electric", "Wind"], parent_moves: ["Hurricane", "Sparks", "Tesla Prison", "Turbine", "Turbo Charge"] },
    "Oceara": { family: "Oceara", type: ["Water"], parent_moves: ["Flood", "High-pressure Water", "Ice Shuriken", "Sharp Rain"] },
    "Yowlar": { family: "Yowlar", type: ["Neutral"], parent_moves: ["Clinch", "Oshi-Dashi", "Toughen"] },
    "Droply": { family: "Droply", type: ["Water", "Earth"], parent_moves: ["Ice Cubes"] },
    "Garyo": { family: "Droply", type: ["Water", "Earth"], parent_moves: ["Antitoxins", "Chain Heal", "Cold Geyser", "Earthbreaker", "Flood", "Ice Cubes", "Iced Stalactite"] },
    "Broccoblin": { family: "Broccoblin", type: ["Nature"], parent_moves: ["Bark Shield", "Frond Whip", "Photosynthesis", "Spores"] },
    "Broccorc": { family: "Broccoblin", type: ["Nature", "Melee"], parent_moves: ["Bark Shield", "Bush", "Dim Mak", "Frond Whip", "Martial Strike", "Photosynthesis", "Soul Shout", "Spores"] },
    "Broccolem": { family: "Broccoblin", type: ["Nature", "Melee"], parent_moves: ["Bark Shield", "Bush", "Dim Mak", "Frond Whip", "Martial Strike", "Photosynthesis", "Soul Shout", "Spores"] },
    "Shuine": { family: "Shuine", type: ["Crystal", "Water"], parent_moves: ["Antitoxins", "Crystal Bite", "Flood", "Iced Stalactite", "Mirror Shell", "Ninja Jutsu", "Quartz Shield"] },
    "Nessla": { family: "Nessla", type: ["Water", "Electric"], parent_moves: ["Bubbles", "Iced Stalactite", "Piezoelectric Blow", "Sparks", "Strangle", "Tesla Prison", "Thunder Strike"] },
    "Valiar": { family: "Valiar", type: ["Mental"], parent_moves: ["Denigrate", "Extra Energy Slam", "Hypnosis", "Psy Surge", "Ultrasound"] },
    "Pupoise": { family: "Pupoise", type: ["Digital", "Nature"], parent_moves: ["Bush", "Frond Whip", "Roots"] },
    "Loatle": { family: "Pupoise", type: ["Digital", "Mental"], parent_moves: ["Autodestruction", "Blue Screen", "Bush", "Energy Manipulation", "Frond Whip", "Matter Teleport", "Ninja Jutsu", "Telekinetic Shrapnel"] },
    "Kalazu": { family: "Kalazu", type: ["Water"], parent_moves: ["Bubbles", "High-pressure Water", "Strangle"] },
    "Kalabyss": { family: "Kalazu", type: ["Water", "Toxic"], parent_moves: ["Bubbles", "Flood", "High-pressure Water", "Rotten Goo", "Strangle", "Toxic Ink", "Waterjet"] },
    "Adoroboros": { family: "Adoroboros", type: ["Toxic", "Mental"], parent_moves: ["Antitoxins", "Denigrate", "Energy Manipulation", "Hypnosis", "Inner Spirit", "Sacrifice", "Virulent Gust"] },
    "Tuwai": { family: "Tuwai", type: ["Wind"], parent_moves: ["Feather Gatling", "Humiliating Slap", "Tornado"] },
    "Tukai": { family: "Tuwai", type: ["Wind", "Water"], parent_moves: ["Feather Gatling", "Humiliating Slap", "Sharp Rain", "Tornado", "Waterjet"] },
    "Tulcan": { family: "Tuwai", type: ["Wind", "Fire"], parent_moves: ["Feather Gatling", "Fiery Heist", "Humiliating Slap", "Tornado"] },
    "Tuvine": { family: "Tuwai", type: ["Wind", "Crystal"], parent_moves: ["Diamond Fort", "Feather Gatling", "Humiliating Slap", "Mirror Shell", "Tornado"] },
    "Turoc": { family: "Tuwai", type: ["Wind", "Earth"], parent_moves: ["Feather Gatling", "Humiliating Slap", "Tornado", "Turbine"] },
    "Tuwire": { family: "Tuwai", type: ["Wind", "Digital"], parent_moves: ["Feather Gatling", "Hologram", "Humiliating Slap", "Tornado", "Turbo Attack"] },
    "Tutsu": { family: "Tuwai", type: ["Wind", "Melee"], parent_moves: ["Feather Gatling", "Haito Uchi", "Humiliating Slap", "Show Off", "Tornado", "Wrenching Massage"] },
    "Kinu": { family: "Kinu", type: ["Nature", "Mental"], parent_moves: ["Beta Burst", "Hypnosis", "Lifeful Sap", "Revitalize", "Sacrifice"] },
    "Vulvir": { family: "Vulvir", type: ["Fire", "Earth"], parent_moves: ["Earth Wave", "Hook"] },
    "Vulor": { family: "Vulvir", type: ["Fire", "Earth"], parent_moves: ["Earth Wave", "Hook"] },
    "Vulcrane": { family: "Vulvir", type: ["Fire", "Earth"], parent_moves: ["Earth Wave", "Hook", "Roar"] },
    "Pigepic": { family: "Pigepic", type: ["Wind"], parent_moves: ["Hurricane", "Oshi-Dashi", "Sharp Rain", "Tornado", "Turbine"] },
    "Akranox": { family: "Akranox", type: ["Earth", "Toxic"], parent_moves: ["Earth Wave", "Intimidation", "Metabolize", "Mud Shower", "Toughen"] },
    
    // Koish Variants (Always Primary: Water)
    "Koish (Neutral)": { family: "Koish (Neutral)", type: ["Water", "Neutral"], parent_moves: ["Autodestruction"] },
    "Koish (Fire)": { family: "Koish (Fire)", type: ["Water", "Fire"], parent_moves: ["Autodestruction"] },
    "Koish (Water)": { family: "Koish (Water)", type: ["Water"], parent_moves: ["Autodestruction"] },
    "Koish (Nature)": { family: "Koish (Nature)", type: ["Water", "Nature"], parent_moves: ["Autodestruction"] },
    "Koish (Electric)": { family: "Koish (Electric)", type: ["Water", "Electric"], parent_moves: ["Autodestruction"] },
    "Koish (Earth)": { family: "Koish (Earth)", type: ["Water", "Earth"], parent_moves: ["Autodestruction"] },
    "Koish (Mental)": { family: "Koish (Mental)", type: ["Water", "Mental"], parent_moves: ["Autodestruction"] },
    "Koish (Wind)": { family: "Koish (Wind)", type: ["Water", "Wind"], parent_moves: ["Autodestruction"] },
    "Koish (Digital)": { family: "Koish (Digital)", type: ["Water", "Digital"], parent_moves: ["Autodestruction"] },
    "Koish (Melee)": { family: "Koish (Melee)", type: ["Water", "Melee"], parent_moves: ["Autodestruction"] },
    "Koish (Crystal)": { family: "Koish (Crystal)", type: ["Water", "Crystal"], parent_moves: ["Autodestruction"] },
    "Koish (Toxic)": { family: "Koish (Toxic)", type: ["Water", "Toxic"], parent_moves: ["Autodestruction"] },

    "Vulffy": { family: "Vulffy", type: ["Earth", "Nature"], parent_moves: ["Bush", "Dust Vortex", "Jinxed Whisper", "Lifeful Sap", "Petal Dagger"] },
    "Chubee": { family: "Chubee", type: ["Digital", "Wind"], parent_moves: [] },
    "Waspeen": { family: "Chubee", type: ["Digital", "Crystal"], parent_moves: [] },
    "Mawtle": { family: "Mawtle", type: ["Digital", "Nature"], parent_moves: ["Digithreat", "Revitalize", "Spores"] },
    "Mawmense": { family: "Mawtle", type: ["Digital", "Nature"], parent_moves: ["Digithreat", "Plasma Beam", "Revitalize", "Roots", "Spores"] },
    "Hazrat": { family: "Hazrat", type: ["Toxic", "Fire"], parent_moves: ["Metabolize"] },
    "Minttle": { family: "Minttle", type: ["Mental"], parent_moves: ["Energy Manipulation"] },
    "Minox": { family: "Minttle", type: ["Mental", "Electric"], parent_moves: ["Energy Manipulation", "Sparkling Bullet", "Thunder Strike"] },
    "Minothor": { family: "Minttle", type: ["Mental", "Electric"], parent_moves: ["Energy Manipulation", "Piezoelectric Blow", "Sparkling Bullet", "Thunder Strike"] },
    "Maoala": { family: "Maoala", type: ["Melee", "Mental"], parent_moves: ["Hypnosis", "Jinxed Whisper", "Meditation"] },
    "Venx": { family: "Venx", type: ["Neutral"], parent_moves: ["Ninja Jutsu"] },
    "Venmet": { family: "Venx", type: ["Neutral", "Melee"], parent_moves: ["Hook Kick", "Ninja Jutsu", "Unseen Blow"] },
    "Vental": { family: "Venx", type: ["Neutral", "Mental"], parent_moves: ["Beta Burst", "Denigrate", "Ninja Jutsu", "Psy Surge", "Sacrifice", "Strangle"] },
    "Chimurian": { family: "Chimurian", type: ["Nature", "Crystal"], parent_moves: ["Burrow", "Frond Whip", "Mirror Shell"] },
    "Arachnyte": { family: "Arachnyte", type: ["Neutral", "Digital"], parent_moves: ["Digithreat", "Knockback", "Unseen Blow"] },
    "Thaiko": { family: "Thaiko", type: ["Digital", "Melee"], parent_moves: ["Dim Mak", "Hook", "Martial Strike", "Plasma Beam", "Unseen Blow"] },
    "Monkko": { family: "Thaiko", type: ["Digital", "Melee"], parent_moves: ["Dim Mak", "Hook", "Martial Strike", "Ninja Jutsu", "Plasma Beam", "Soul Shout", "Unseen Blow"] },
    "Anahir": { family: "Anahir", type: ["Crystal", "Fire"], parent_moves: ["Chain Heal", "Crystal Bite", "Fiery Heist", "Heat Up", "Mineral Hail", "Rampage"] },
    "Anatan": { family: "Anahir", type: ["Crystal", "Fire"], parent_moves: ["Chain Heal", "Crystal Bite", "Fiery Heist", "Heat Up", "Mineral Hail", "Rampage"] },
    "Tyranak": { family: "Tyranak", type: ["Fire", "Nature"], parent_moves: []},
    "Volgon": { family: "Volgon", type: ["Electric"], parent_moves: []},
    "Galios": { family: "Galios", type: ["Mental", "Earth"], parent_moves: [] }
};